dist: trusty
sudo: false
language: python
python:
  - '2.7'


# Install the packages needed for the build.
#  lib32z1 is needed to run 32bit programs, in this case the GCC crosscompiler
#  from "gcc-arm-embedded" (https://launchpad.net/gcc-arm-embedded).
addons:
  apt:
    packages:
      - lib32z1


# Cache the .mbs folder.
cache:
  directories:
  - $HOME/.mbs


# This is the command to build the whole project and pack the results in a distributable form.
script:
  - python2.7 mbs/mbs
